# Generated by Django 2.2.12 on 2021-05-31 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NaturadietApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noticia',
            name='update',
        ),
    ]
