# Generated by Django 2.2.12 on 2021-05-31 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NaturadietApp', '0002_remove_noticia_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_column='CREATED'),
        ),
    ]
