# Generated by Django 2.2.12 on 2021-05-31 23:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NaturadietApp', '0003_auto_20210531_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.ForeignKey(db_column='ROL', default=2, null=True, on_delete=django.db.models.deletion.CASCADE, to='NaturadietApp.Rol'),
        ),
    ]
