# Generated by Django 2.2.12 on 2021-06-01 21:15

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NaturadietApp', '0004_auto_20210531_2339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='contenido',
            field=ckeditor.fields.RichTextField(db_column='CONTENIDO'),
        ),
    ]
