# Generated by Django 2.2.12 on 2021-06-02 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NaturadietApp', '0005_auto_20210601_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='nombre',
            field=models.CharField(db_column='NOMBRE', max_length=50),
        ),
    ]
