# Generated by Django 2.2.12 on 2021-06-03 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NaturadietApp', '0006_auto_20210602_1926'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='producto',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='Factura',
        ),
        migrations.DeleteModel(
            name='Pedido',
        ),
        migrations.DeleteModel(
            name='Producto',
        ),
    ]
