# Generated by Django 2.2.12 on 2021-06-03 15:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NaturadietApp', '0007_auto_20210603_1524'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaProducto',
            fields=[
                ('id_categoria', models.AutoField(db_column='ID_CATEGORIA', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='NOMBRE', max_length=50)),
            ],
            options={
                'db_table': 'CATEGORIA_PRODUCTO',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.AutoField(db_column='ID_PRODUCTO', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='NOMBRE', max_length=255)),
                ('imagen', models.ImageField(db_column='IMAGEN', upload_to='Productos')),
                ('descripcion', models.CharField(blank=True, db_column='DESCRIPCION', max_length=255, null=True)),
                ('precio', models.DecimalField(db_column='PRECIO', decimal_places=2, max_digits=5)),
                ('categoria', models.ForeignKey(db_column='CATEGORIA', on_delete=django.db.models.deletion.CASCADE, to='NaturadietApp.CategoriaProducto')),
            ],
            options={
                'db_table': 'PRODUCTO',
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id_pedido', models.AutoField(db_column='ID_PEDIDO', primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(auto_now_add=True, db_column='FECHA')),
                ('producto', models.ForeignKey(db_column='PRODUCTO', on_delete=django.db.models.deletion.CASCADE, to='NaturadietApp.Producto')),
                ('usuario', models.ForeignKey(db_column='USUARIO', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'PEDIDO',
            },
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('importe', models.DecimalField(blank=True, db_column='IMPORTE', decimal_places=2, max_digits=5, null=True)),
                ('cantidad', models.IntegerField(blank=True, db_column='CANTIDAD', null=True)),
                ('pedido', models.ForeignKey(db_column='PEDIDO', on_delete=django.db.models.deletion.CASCADE, to='NaturadietApp.Pedido')),
                ('producto', models.ForeignKey(db_column='PRODUCTO', on_delete=django.db.models.deletion.CASCADE, to='NaturadietApp.Producto')),
            ],
            options={
                'db_table': 'FACTURA',
                'unique_together': {('pedido', 'producto')},
            },
        ),
    ]
