# Generated by Django 2.2.12 on 2021-06-03 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NaturadietApp', '0009_producto_disponibilidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='disponibilidad',
            field=models.BooleanField(db_column='DISPONIBILIDAD', default=True),
        ),
    ]
