# Generated by Django 2.2.12 on 2021-06-03 15:57

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NaturadietApp', '0010_auto_20210603_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=ckeditor.fields.RichTextField(blank=True, db_column='DESCRIPCION', max_length=255, null=True),
        ),
    ]
