# Generated by Django 2.2.12 on 2021-06-04 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NaturadietApp', '0011_auto_20210603_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caloria',
            name='genero',
            field=models.CharField(choices=[('HOMBRE', 'Hombre'), ('MUJER', 'Mujer')], db_column='GENERO', default=('HOMBRE', 'Hombre'), max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='caloria',
            name='persona',
            field=models.CharField(choices=[('ADOLESCENTE', 'Adolescente'), ('ADULTO', 'Adulto'), ('ANCIANO', 'Anciano')], db_column='PERSONA', default=('ADOLESCENTE', 'Adolescente'), max_length=30, null=True),
        ),
    ]
