# Generated by Django 2.2.12 on 2021-06-04 07:46

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NaturadietApp', '0012_auto_20210604_0737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dieta',
            name='domingo',
            field=ckeditor.fields.RichTextField(db_column='DOMINGO'),
        ),
        migrations.AlterField(
            model_name='dieta',
            name='jueves',
            field=ckeditor.fields.RichTextField(db_column='JUEVES'),
        ),
        migrations.AlterField(
            model_name='dieta',
            name='lunes',
            field=ckeditor.fields.RichTextField(db_column='LUNES'),
        ),
        migrations.AlterField(
            model_name='dieta',
            name='martes',
            field=ckeditor.fields.RichTextField(db_column='MARTES'),
        ),
        migrations.AlterField(
            model_name='dieta',
            name='miercoles',
            field=ckeditor.fields.RichTextField(db_column='MIERCOLES'),
        ),
        migrations.AlterField(
            model_name='dieta',
            name='sabado',
            field=ckeditor.fields.RichTextField(db_column='SABADO'),
        ),
        migrations.AlterField(
            model_name='dieta',
            name='viernes',
            field=ckeditor.fields.RichTextField(db_column='VIERNES'),
        ),
    ]
