# Generated by Django 2.2.12 on 2021-06-08 04:41

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NaturadietApp', '0013_auto_20210604_0746'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='producto',
        ),
        migrations.AddField(
            model_name='estado',
            name='descripcion',
            field=ckeditor.fields.RichTextField(db_column='DESCRIPCION', null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='total',
            field=models.DecimalField(blank=True, db_column='IMPORTE', decimal_places=2, max_digits=5, null=True),
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='dieta',
        ),
        migrations.AddField(
            model_name='usuario',
            name='dieta',
            field=models.ManyToManyField(blank=True, db_column='DIETA', to='NaturadietApp.Dieta'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='provincia',
            field=models.CharField(choices=[('A Coruña', 'A Coruña'), ('Álava', 'Álava'), ('Albacete', 'Albacete'), ('Alicante', 'Alicante'), ('Almería', 'Almería'), ('Asturias', 'Asturias'), ('Ávila', 'Ávila'), ('Badajoz', 'Badajoz'), ('Baleares', 'Baleares'), ('Barcelona', 'Barcelona'), ('Burgos', 'Burgos'), ('Cáceres', 'Cáceres'), ('Cádiz', 'Cádiz'), ('Cantabria', 'Cantabria'), ('Castellón', 'Castellón'), ('Ciudad Real', 'Ciudad Real'), ('Córdoba', 'Córdoba'), ('Cuenca', 'Cuenca'), ('Girona', 'Girona'), ('Granada', 'Granada'), ('Guadalajara', 'Guadalajara'), ('Gipuzkoa', 'Gipuzkoa'), ('Huelva', 'Huelva'), ('Huesca', 'Huesca'), ('Jaén', 'Jaén'), ('La Rioja', 'La Rioja'), ('Las Palmas', 'Las Palmas'), ('León', 'León'), ('Lérida', 'Lérida'), ('Lugo', 'Lugo'), ('Madrid', 'Madrid'), ('Málaga', 'Málaga'), ('Murcia', 'Murcia'), ('Navarra', 'Navarra'), ('Ourense', 'Ourense'), ('Palencia', 'Palencia'), ('Pontevedra', 'Pontevedra'), ('Salamanca', 'Salamanca'), ('Segovia', 'Segovia'), ('Sevilla', 'Sevilla'), ('Soria', 'Soria'), ('Tarragona', 'Tarragona'), ('Santa Cruz de Tenerife', 'Santa Cruz de Tenerife'), ('Teruel', 'Teruel'), ('Toledo', 'Toledo'), ('Valencia', 'Valencia'), ('Valladolid', 'Valladolid'), ('Vizcaya', 'Vizcaya'), ('Zamora', 'Zamora'), ('Zaragoza', 'Zaragoza')], db_column='PROVINCIA', max_length=30, null=True),
        ),
    ]
