# Generated by Django 2.2.12 on 2021-06-10 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NaturadietApp', '0014_auto_20210608_0441'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='descripcion',
            field=models.CharField(blank=True, db_column='DESCRIPCION', max_length=500, null=True),
        ),
    ]
