# Generated by Django 2.2.12 on 2021-06-10 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NaturadietApp', '0015_usuario_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='entregado',
            field=models.BooleanField(db_column='ENTREGADO', default=False),
        ),
    ]
