# Generated by Django 2.2.12 on 2021-06-11 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NaturadietApp', '0016_pedido_entregado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='altura',
            field=models.DecimalField(db_column='ALTURA', decimal_places=2, max_digits=3),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='edad',
            field=models.IntegerField(db_column='EDAD'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='genero',
            field=models.CharField(choices=[('HOMBRE', 'Hombre'), ('MUJER', 'Mujer')], db_column='GENERO', default=('HOMBRE', 'Hombre'), max_length=30),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='peso',
            field=models.IntegerField(db_column='PESO'),
        ),
    ]
