# Generated by Django 2.2.12 on 2021-06-14 05:59

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NaturadietApp', '0017_auto_20210611_0259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='contenido',
            field=ckeditor.fields.RichTextField(db_column='CONTENIDO', max_length=1000),
        ),
    ]
